# Generated by Django 5.1.7 on 2025-04-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('SM', 'Scrum Master'), ('TL', 'Team Lead'), ('D', 'Developer'), ('QA', 'Quality Assurance'), ('V', 'View Only')], default='V', max_length=50),
        ),
    ]
