# Generated by Django 5.1.7 on 2025-04-04 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='user',
        ),
    ]
