# Generated by Django 5.1.7 on 2025-04-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0003_rename_user_id_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='@email.com', max_length=254),
        ),
    ]
