# Generated by Django 5.1.7 on 2025-04-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('O', 'Open'), ('P', 'Pending'), ('C', 'Completed'), ('IP', 'In Progress')], default='Open', max_length=20)),
            ],
        ),
    ]
